//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.Service.Application.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Identity.Service.Application.Constants.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be Alphanumeric.
        /// </summary>
        public static string AlphanumericPassword {
            get {
                return ResourceManager.GetString("AlphanumericPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API call Ends with exception..
        /// </summary>
        public static string ApiLogsFail {
            get {
                return ResourceManager.GetString("ApiLogsFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API call Ends. .
        /// </summary>
        public static string ApiLogsSuccess {
            get {
                return ResourceManager.GetString("ApiLogsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication cookie is missing or empty..
        /// </summary>
        public static string AuthenticationCookieIsMissing {
            get {
                return ResourceManager.GetString("AuthenticationCookieIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully for user.
        /// </summary>
        public static string ChangedPassword {
            get {
                return ResourceManager.GetString("ChangedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been received. Our team will contact you shortly..
        /// </summary>
        public static string ContactUsEmailReceived {
            get {
                return ResourceManager.GetString("ContactUsEmailReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send contact us email {0}..
        /// </summary>
        public static string ContactUsEmailSendFailed {
            get {
                return ResourceManager.GetString("ContactUsEmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be a valid email address..
        /// </summary>
        public static string ContactUsInvalidEmail {
            get {
                return ResourceManager.GetString("ContactUsInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be at least 1..
        /// </summary>
        public static string ContactUsInvalidQuantity {
            get {
                return ResourceManager.GetString("ContactUsInvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save your request. Please try again..
        /// </summary>
        public static string ContactUsSaveFailed {
            get {
                return ResourceManager.GetString("ContactUsSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database error occurred. Please check your input and try again..
        /// </summary>
        public static string DatabaseErrorContactUs {
            get {
                return ResourceManager.GetString("DatabaseErrorContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department not found..
        /// </summary>
        public static string DepartmentNotFound {
            get {
                return ResourceManager.GetString("DepartmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments not found..
        /// </summary>
        public static string DepartmentsNotFound {
            get {
                return ResourceManager.GetString("DepartmentsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateEmail.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Exists.
        /// </summary>
        public static string DuplicateEmailaddress {
            get {
                return ResourceManager.GetString("DuplicateEmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicateUserName.
        /// </summary>
        public static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not register.
        /// </summary>
        public static string EmailNotRegister {
            get {
                return ResourceManager.GetString("EmailNotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        public static string EmailSendSuccess {
            get {
                return ResourceManager.GetString("EmailSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send password reset email..
        /// </summary>
        public static string FailedToSendPasswordResetEmail {
            get {
                return ResourceManager.GetString("FailedToSendPasswordResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send password reset email for user {UserId}..
        /// </summary>
        public static string FailedToSendPasswordResetEmailUserId {
            get {
                return ResourceManager.GetString("FailedToSendPasswordResetEmailUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished handling request: {Url} with status {StatusCode}.
        /// </summary>
        public static string FinishedRequest {
            get {
                return ResourceManager.GetString("FinishedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forget password email sent.
        /// </summary>
        public static string ForgetPasswordEmailSent {
            get {
                return ResourceManager.GetString("ForgetPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated password reset token for.
        /// </summary>
        public static string GeneratedResetPassword {
            get {
                return ResourceManager.GetString("GeneratedResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling request: {Url}.
        /// </summary>
        public static string HandleRequest {
            get {
                return ResourceManager.GetString("HandleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while processing {Url}.
        /// </summary>
        public static string HandleRequestException {
            get {
                return ResourceManager.GetString("HandleRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive User.
        /// </summary>
        public static string InactiveUser {
            get {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industries not found..
        /// </summary>
        public static string IndustriesNotFound {
            get {
                return ResourceManager.GetString("IndustriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry not found..
        /// </summary>
        public static string IndustryNotFound {
            get {
                return ResourceManager.GetString("IndustryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Memory Database Not Created.
        /// </summary>
        public static string InMemoryDataBaseNotCreated {
            get {
                return ResourceManager.GetString("InMemoryDataBaseNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid document.
        /// </summary>
        public static string InvalidDocument {
            get {
                return ResourceManager.GetString("InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid invite user ID: {InviteUserId}. Please resend email..
        /// </summary>
        public static string InvalidInviteUserId {
            get {
                return ResourceManager.GetString("InvalidInviteUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OTP.
        /// </summary>
        public static string InvalidOTP {
            get {
                return ResourceManager.GetString("InvalidOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid userId.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite user not found.
        /// </summary>
        public static string InviteUserNotFound {
            get {
                return ResourceManager.GetString("InviteUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT secret is missing or invalid..
        /// </summary>
        public static string JwtSecretMissing {
            get {
                return ResourceManager.GetString("JwtSecretMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWTSecret is not configured..
        /// </summary>
        public static string JWTSecretNotConfigured {
            get {
                return ResourceManager.GetString("JWTSecretNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! This Link is expired!.
        /// </summary>
        public static string LinkExpired {
            get {
                return ResourceManager.GetString("LinkExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! This Link is already used!.
        /// </summary>
        public static string LinkUsed {
            get {
                return ResourceManager.GetString("LinkUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login Successfully.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout Successfully.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Deleted.
        /// </summary>
        public static string NotificationDeleted {
            get {
                return ResourceManager.GetString("NotificationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Updated.
        /// </summary>
        public static string NotificationUpdated {
            get {
                return ResourceManager.GetString("NotificationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password not correct.
        /// </summary>
        public static string OldPasswordNotCorrect {
            get {
                return ResourceManager.GetString("OldPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP expired.
        /// </summary>
        public static string OTPExpired {
            get {
                return ResourceManager.GetString("OTPExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in sending OTP.
        /// </summary>
        public static string OTPFailed {
            get {
                return ResourceManager.GetString("OTPFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password and new password cannot be same.
        /// </summary>
        public static string PasswordCannotBeSame {
            get {
                return ResourceManager.GetString("PasswordCannotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset Request.
        /// </summary>
        public static string PasswordResetReq {
            get {
                return ResourceManager.GetString("PasswordResetReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successful.
        /// </summary>
        public static string PasswordResetSuccessful {
            get {
                return ResourceManager.GetString("PasswordResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successful for user ID: {UserId}..
        /// </summary>
        public static string PasswordResetSuccessfulForUserId {
            get {
                return ResourceManager.GetString("PasswordResetSuccessfulForUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized. Please contact administrator.
        /// </summary>
        public static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Provide Password to Continue.
        /// </summary>
        public static string ProvidePassword {
            get {
                return ResourceManager.GetString("ProvidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please resend email.
        /// </summary>
        public static string ResendEmail {
            get {
                return ResourceManager.GetString("ResendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully reset..
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email.
        /// </summary>
        public static string SendEmailFailed {
            get {
                return ResourceManager.GetString("SendEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP sent Successfully.
        /// </summary>
        public static string SentOTPSuccess {
            get {
                return ResourceManager.GetString("SentOTPSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Database Connected in Testing.
        /// </summary>
        public static string ServerDataBaseConnectedInTesting {
            get {
                return ResourceManager.GetString("ServerDataBaseConnectedInTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string StatusFail {
            get {
                return ResourceManager.GetString("StatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string StatusInfo {
            get {
                return ResourceManager.GetString("StatusInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string StatusSuccess {
            get {
                return ResourceManager.GetString("StatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Updated.
        /// </summary>
        public static string StatusUpdated {
            get {
                return ResourceManager.GetString("StatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string StatusWarning {
            get {
                return ResourceManager.GetString("StatusWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token has been expired.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many Request, Please try again after few minutes.
        /// </summary>
        public static string TooManyRequest {
            get {
                return ResourceManager.GetString("TooManyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while processing your request..
        /// </summary>
        public static string UnexpectedErrorContactUs {
            get {
                return ResourceManager.GetString("UnexpectedErrorContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error processing ContactUs for {Email}.
        /// </summary>
        public static string UnexpectedErrorContactUsEmail {
            get {
                return ResourceManager.GetString("UnexpectedErrorContactUsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownValidationError {
            get {
                return ResourceManager.GetString("UnknownValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {UserId} is active and email is confirmed..
        /// </summary>
        public static string UserActiveAndEmailConfirmed {
            get {
                return ResourceManager.GetString("UserActiveAndEmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User:{InviteUserId} attempted to reuse the same password..
        /// </summary>
        public static string UserAttemptedToReusePassword {
            get {
                return ResourceManager.GetString("UserAttemptedToReusePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created successfully.
        /// </summary>
        public static string UserCreatedSuccess {
            get {
                return ResourceManager.GetString("UserCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {UserId} is either inactive or email not confirmed..
        /// </summary>
        public static string UserInactiveOrEmailNotConfirmed {
            get {
                return ResourceManager.GetString("UserInactiveOrEmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated successfully!.
        /// </summary>
        public static string UserProfileUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("UserProfileUpdatedSuccessMessage", resourceCulture);
            }
        }
    }
}
